from . import medical_specialty
from . import medical_patient
from . import medical_practitioner
from . import medical_study_type
from . import medical_examination_template
from . import medical_examination_order
from . import medical_study_request
from . import medical_study_result
from . import medical_certificate
